spring:
  profiles:
    active: dev

server:
  servlet:
    context-path: /est
  port: 8080

#mybatis
mybatis:
  mapper-locations: classpath:/cn/est/mapper/*.xml




#非空配置
param:
  notNull:
    /api/sms/verifyCode=phone&codeType, /api/user/login/sms=phone&sms, /api/evaluate/specList=modelId, /api/evaluate/assess=optionIds&modelId,/api/order/maintain/submit=evaluateId&phone&appintDate&temporalInterval&adress&sms